
iter_files = {  ...
          ...      sprintf('Physical_Marshak/Iteration_Status/MW_Physical_S8_P3_100C_Volumetric_1P_1C_iteration_status.txt'); ...
          sprintf('Physical_Marshak/Iteration_Status/MW_Physical_S8_P3_100C_Volumetric_1P_50C_iteration_status.txt'); ...
          sprintf('Physical_Marshak/Iteration_Status/MW_Physical_S8_P3_100C_Volumetric_1P_25C_iteration_status.txt'); ...
          sprintf('Physical_Marshak/Iteration_Status/MW_Physical_S8_P3_100C_Volumetric_1P_10C_iteration_status.txt'); ...
           sprintf('Physical_Marshak/Iteration_Status/MW_Physical_S8_P3_100C_Volumetric_1P_5C_iteration_status.txt'); ...
                sprintf('Physical_Marshak/Iteration_Status/MW_Physical_S8_P3_100C_Volumetric_1P_2C_iteration_status.txt'); ...                
                    ...      sprintf('Physical_Marshak/Iteration_Status/MW_Physical_S8_P3_100C_Volumetric_1P_100C_iteration_status.txt'); ...
                };
            

            
max_steps = [ 133000 ; 100000 ; 100000 ;100000 ;100000 ;100000 ;] ;
Plot_dt_Trace_in_Time(iter_files,max_steps)
h = legend('Volumetric $N_{cg}=50$','Volumetric $N_{cg}=25$','Volumetric $N_{cg}=10$','Volumetric $N_{cg}=5$','Volumetric $N_{cg}=2$','Location','NorthWest');
set(h,'Interpreter','latex','FontSize',24)
% 

% 
SavePretty(gcf,'Volumetric_traces_in_time')


