% % % save better radtran results
files = { sprintf('MMS2_TL_phi_L2') ; ...
sprintf('MMS2_SLXS_Lobatto_phi_L2') ; ...
sprintf('MMS2_SLXS_Gauss_phi_L2') ; ...
sprintf('MMS2_TL_temp_L2') ; ...
sprintf('MMS2_SLXS_Lobatto_temp_L2') ; ...
sprintf('MMS2_SLXS_Gauss_temp_L2') ; ...
sprintf('MMS2_SLXS_Lobatto_phi_A') ; ...
sprintf('MMS2_SLXS_Gauss_phi_A') ; ...
sprintf('MMS2_SLXS_Lobatto_temp_A') ; ...
sprintf('MMS2_SLXS_Gauss_temp_A') ; ...
sprintf('MMS3_Constant_XS_SL_Lobatto_phi_L2') ; ...
sprintf('MMS3_Constant_XS_SL_Gauss_phi_L2') ; ...
sprintf('MMS3_Constant_XS_SL_Lobatto_temp_L2') ; ...
sprintf('MMS3_Constant_XS_SL_Gauss_temp_L2') ; ...
sprintf('MMS3_Constant_XS_SL_Lobatto_temp_A') ; ...
sprintf('MMS3_Constant_XS_SL_Gauss_temp_A') ; ...
sprintf('MMS3_SLXS_Initial_SLXS_Lobatto_phi_L2') ; ...
sprintf('MMS3_SLXS_Initial_SLXS_Gauss_phi_L2') ; ...
sprintf('MMS3_SLXS_Initial_SLXS_Lobatto_temp_L2') ; ...
sprintf('MMS3_SLXS_Initial_SLXS_Gauss_temp_L2') ; ...
sprintf('MMS3_SLXS_Initial_SLXS_Lobatto_phi_A') ; ...
sprintf('MMS3_SLXS_Initial_SLXS_Gauss_phi_A') ; ...
sprintf('MMS3_SLXS_Initial_SLXS_Lobatto_temp_A') ; ...
sprintf('MMS3_SLXS_Initial_SLXS_Gauss_temp_A') ; ...
sprintf('Constant_Time_SLXS_Lobatto_phi_L2') ; ...
sprintf('Constant_Time_SLXS_Gauss_phi_L2') ; ...
sprintf('Constant_Time_SLXS_Lobatto_temp_L2') ; ...
sprintf('Constant_Time_SLXS_Gauss_temp_L2') ; ...
sprintf('Constant_Time_SLXS_Lobatto_phi_A') ; ...
sprintf('Constant_Time_SLXS_Gauss_phi_A') ; ...
sprintf('Constant_Time_SLXS_Lobatto_temp_A') ; ...
sprintf('Constant_Time_SLXS_Gauss_temp_A') ; ...
sprintf('Extended_Time_Integrators_Convergence_Phi') ; ...
sprintf('Extended_Time_Integrators_Convergence_Temperature_Big_dt') ; ...
sprintf('Extended_Time_Integrators_Convergence_Temperature_Small_dt') ; ...
sprintf('Blading_Radiation_Full_MultiCell') ; ...
sprintf('Blading_Temperature_Full_MultiCell') ; ...
sprintf('Blading_Temperature_Zoom_MultiCell') ; ...
sprintf('Reorder_Marshak_Zoom_Radiation_SL_Lobatto_P1_Cell_Refinement') ; ...
sprintf('Reorder_Marshak_Zoom_Temperature_SL_Lobatto_P1_Cell_Refinement') ; ...
sprintf('Reorder_Marshak_Zoom_Radiation_SL_Gauss_P4_Cell_Refinement') ; ...
sprintf('Reorder_Marshak_Zoom_Temperature_SL_Gauss_P4_Cell_Refinement') ; ...
sprintf('Pointless_Marshak_Zoom_Radiation_Lobatto_P_Refinement') ; ...
sprintf('Pointless_Marshak_Zoom_Temperature_Lobatto_P_Refinement') ; ...
sprintf('Time_Refinement_Zoom_Radiation') ; ...
sprintf('Time_Refinement_Zoom_Temperature') ; ...
sprintf('Zoom_10k_Temperature') };

n=length(files)

for i=1:1:n
   open(sprintf('%s.fig',char(files(i))))
   SavePretty(gcf, char(files(i)) );
   close all
end