% % plot the convergence of P1 SL Lobatto for mesh refinement
function SpaceTime_Plot(p_ord)
close all


cell_base = { sprintf('Marshak_Results/SL_Lobatto_P%i_20_cell',p_ord) ...
                 'Marshak_Results/SL_Lobatto_P1_80_cell' ...
                 'Marshak_Results/SL_Lobatto_P1_320_cell' ...
                 'Marshak_Results/SL_Lobatto_P1_1280_cell' };
             
data_base = { 'Marshak_Results/Marshak_Wave_SL_Lobatto_P1_Base' ...
                'Marshak_Results/Marshak_Wave_SL_Lobatto_P1_Base_Refine_4_Cells_1_Time' ...
                'Marshak_Results/Marshak_Wave_SL_Lobatto_P1_Base_Refine_16_Cells_1_Time' ...
                'Marshak_Results/Marshak_Wave_SL_Lobatto_P1_Base_Refine_64_Cells_1_Time' };
            
Dark_Arts_Plotter(2,3,cell_base,data_base)

cell_base = {'Marshak_Results/SL_Lobatto_P1_1280_cell' };
data_base = {'Marshak_Results/Marshak_Wave_SL_Lobatto_P1_Base_Refine_64_Cells_1_Time' ...
                'Marshak_Results/Marshak_Wave_SL_Lobatto_P1_Base_Refine_64_Cells_4_Time' ...
            'Marshak_Results/Marshak_Wave_SL_Lobatto_P1_Base_Refine_64_Cells_16_Time' ...
            'Marshak_Results/Marshak_Wave_SL_Lobatto_P1_Base_Refine_64_Cells_64_Time' };
        
Dark_Arts_Plotter(4,5 , cell_base, data_base);

return
end