% % % plot solutions
% close all


[quad_pt , w] = lglnodes(2);

p_ord = length(quad_pt) - 1;


% cell_base = { ...sprintf('Su_Olson/Su_Olson_Base_SLXS_Lobatto_Tau_10_32angle') ...
%                sprintf('Su_Olson/Su_Olson_SLXS_Lobatto_Tau_1_No_Reflection_S2') ...
%                sprintf('Su_Olson/Su_Olson_SLXS_Lobatto_Tau_1_No_Reflection_S8') ...
%                sprintf('Su_Olson/Su_Olson_SLXS_Lobatto_Tau_1_No_Reflection_S32') ...
%                sprintf('Su_Olson/Su_Olson_SLXS_Lobatto_Tau_1_No_Reflection_S2_1em6') ...
%                 sprintf('Su_Olson/Su_Olson_SLXS_Lobatto_Tau_1_No_Reflection_S2_1em4') ...
%                 };
%              
% data_base = {   sprintf('Su_Olson/Su_Olson_SLXS_Lobatto_Tau_1_No_Reflection_S2') ...
%                 sprintf('Su_Olson/Su_Olson_SLXS_Lobatto_Tau_1_No_Reflection_S8') ...
%                 sprintf('Su_Olson/Su_Olson_SLXS_Lobatto_Tau_1_No_Reflection_S32') ...
%                 sprintf('Su_Olson/Su_Olson_SLXS_Lobatto_Tau_1_No_Reflection_S2_1em6') ...
%                 sprintf('Su_Olson/Su_Olson_SLXS_Lobatto_Tau_1_No_Reflection_S2_1em4') ...
%                 };

% cell_base = { ...sprintf('Su_Olson/Su_Olson_Base_SLXS_Lobatto_Tau_10_32angle') ...
%                sprintf('Su_Olson/Su_Olson_SLXS_Lobatto_Tau_1_No_Reflection_S2_P1_Full') ...
%                sprintf('Su_Olson/Su_Olson_SLXS_Lobatto_Tau_1_No_Reflectio
%                n_S8') ...
%                sprintf('Su_Olson/Su_Olson_SLXS_Lobatto_Tau_1_No_Reflection_S32') ...
%                sprintf('Su_Olson/Su_Olson_SLXS_Lobatto_Tau_1_No_Reflection_S2_1em6') ...
%                 sprintf('Su_Olson/Su_Olson_SLXS_Lobatto_Tau_1_No_Reflection_S2_1em4') ...
%                 };
             
% data_base = {   sprintf('Su_Olson/Su_Olson_SLXS_Lobatto_Tau_1_No_Reflection_S2_P1_Full') ...
%                 sprintf('Su_Olson/Su_Olson_SLXS_Lobatto_Tau_1_No_Reflecti
%                 on_S8') ...
%                 sprintf('Su_Olson/Su_Olson_SLXS_Lobatto_Tau_1_No_Reflection_S32') ...
%                 sprintf('Su_Olson/Su_Olson_SLXS_Lobatto_Tau_1_No_Reflection_S2_1em6') ...
%                 sprintf('Su_Olson/Su_Olson_SLXS_Lobatto_Tau_1_No_Reflection_S2_1em4') ...
%                 };
            
% cell_base = { ...sprintf('Su_Olson/Su_Olson_SLXS_Lobatto_Tau_1_No_Reflection_S2_P1_1em10')...
% ...%                 sprintf('Su_Olson/Su_Olson_SLXS_Lobatto_Tau_1_No_Reflection_S2_P1_1em8')...
%                 sprintf('Su_Olson/Su_Olson_SLXS_Lobatto_Tau_1_No_Reflection_S2_P1_1em8_Extra_Cells')...
% ...%                 sprintf('Su_Olson/Su_Olson_SLXS_Lobatto_Tau_1_No_Reflection_S16_P1_1em8')...           
% ...%                 sprintf('Su_Olson/Su_Olson_SLXS_Lobatto_Tau_1_No_Reflection_S2_P1_1em8_Extra_Time')...
%                 sprintf('Su_Olson/Su_Olson_SLXS_Lobatto_Tau_1_No_Reflection_S16_P1_1em8_Extra_Cells')...
% ...%                 sprintf('Su_Olson/Su_Olson_SLXS_Lobatto_Tau_1_No_Reflection_S16_P1_1em8_Extra_Time')...
%                 sprintf('Su_Olson/Su_Olson_SLXS_Lobatto_Tau_1_S8_1em4')...
%                 sprintf('Su_Olson/Su_Olson_SLXS_Lobatto_Tau_1_S8_1em2')...
%                 sprintf('Su_Olson/Su_Olson_SLXS_Lobatto_Tau_1_S8_1em0')...
%                ... sprintf('Su_Olson/Su_Olson_SLXS_Lobatto_Tau_1_No_Reflection_S2_P1_1em6')
%         };
% data_base = { ...sprintf('Su_Olson/Su_Olson_SLXS_Lobatto_Tau_1_No_Reflection_S2_P1_1em10')...
% ...%                 sprintf('Su_Olson/Su_Olson_SLXS_Lobatto_Tau_1_No_Reflection_S2_P1_1em8')...
%                 sprintf('Su_Olson/Su_Olson_SLXS_Lobatto_Tau_1_No_Reflection_S2_P1_1em8_Extra_Cells')...
% ...%                 sprintf('Su_Olson/Su_Olson_SLXS_Lobatto_Tau_1_No_Reflection_S16_P1_1em8')...           
% ...%                 sprintf('Su_Olson/Su_Olson_SLXS_Lobatto_Tau_1_No_Reflection_S2_P1_1em8_Extra_Time')...
%                 sprintf('Su_Olson/Su_Olson_SLXS_Lobatto_Tau_1_No_Reflection_S16_P1_1em8_Extra_Cells')...
% ...%                 sprintf('Su_Olson/Su_Olson_SLXS_Lobatto_Tau_1_No_Reflection_S16_P1_1em8_Extra_Time')...
%                 sprintf('Su_Olson/Su_Olson_SLXS_Lobatto_Tau_1_S8_1em4')...
%                 sprintf('Su_Olson/Su_Olson_SLXS_Lobatto_Tau_1_S8_1em2')...
%                 sprintf('Su_Olson/Su_Olson_SLXS_Lobatto_Tau_1_S8_1em0')...
%                ...
%                sprintf('Su_Olson/Su_Olson_SLXS_Lobatto_Tau_1_No_Reflection_S2_P1_1em6')

cell_base = {   sprintf('Su_Olson/Su_Olson_SLXS_Lobatto_Tau_1_No_Reflection_S2_P1_1em8_Extra_Time_Extra_Space')...
                sprintf('Su_Olson/Su_Olson_SLXS_Lobatto_Tau_1_No_Reflection_S2_P1_1em8')...    
                sprintf('Su_Olson/Su_Olson_SLXS_Lobatto_Tau_1_S8_1em8_new')...
        };
data_base = {   sprintf('Su_Olson/Su_Olson_SLXS_Lobatto_Tau_1_S8_1em12')...
                sprintf('Su_Olson/Su_Olson_SLXS_Lobatto_Tau_1_S8_1em8')...                
                sprintf('Su_Olson/Su_Olson_SLXS_Lobatto_Tau_1_S8_1em6')...
                sprintf('Su_Olson/Su_Olson_SLXS_Lobatto_Tau_1_S8_1em4')...
                sprintf('Su_Olson/Su_Olson_SLXS_Lobatto_Tau_1_S8_1em2')...
                sprintf('Su_Olson/Su_Olson_SLXS_Lobatto_Tau_1_S8_1em0')...
               };
[dfem_mat,junk] = feshpln( linspace(-1,1,p_ord +3) , quad_pt , p_ord);
            
Su_Olson_Dark_Arts_Plotter(5,6,cell_base,cell_base,dfem_mat)

figure(5)
h = legend('$S_{2}$','$S_2$ Refined','$S_8$ New','Reference');
set(h,'Interpreter','latex');
axis([0 4 0 0.5])

figure(6)

h = legend('$S_{2}','$S_2$ Refined','$S_8$ New','Reference');set(h,'Interpreter','latex');
set(h,'Interpreter','latex');
axis([0 4 0 0.75])

% figure(1)
% legend('S2','S8','S32','S2em6','S2em4')
% axis([0 4 0 1]);
% 
% 
% figure(2)
% legend('S2','S8','S32')
% axis([0 4 0 1]);