% % to be run from /saved in PGM+Dissettation/Dissertation

% %CHapter 3
% % % these files live with the ANE article

% base_location = sprintf('../../SL_XS_Articles/HO_XS_Article_Part_2');
% save_location = sprintf('chapter3_variable_xs');
% 
% file_base_chapter_3 = { sprintf('Psi_Blades') ...
%  sprintf('I_Blades') ...
%  sprintf('SLXS_Psi_Profile') ...
%  sprintf('SLXS_I_Profile') ...
%  sprintf('CXS_Psi_A_Profile') ...
%  sprintf('CXS_I_A_Profile') ...
%  sprintf('FW_Psi_Blades') ...
%  sprintf('FW_I_Blades') ...
% };
% 
% for i = 1:1:length(file_base_chapter_3)
%      open(sprintf('%s/%s.fig',base_location,file_base_chapter_3{i} ) );
%      SavePretty( gcf, sprintf('%s/%s',save_location,file_base_chapter_3{i} ) );
%      close all;
% end


base_location = sprintf('chapter4_acceleration');
save_location = sprintf('chapter4_acceleration');
% Chapter 4
% % these files are all saved in the dissertation directory
file_base_chapter_4 = { sprintf('Const_2_P1_Gauss_Solvers') ...
    sprintf('Const_2_P1_Lobatto_Solvers') ...
... %     sprintf('Const_2_Bar_Constant_XS_SN8_P1_Lobatto_Solvers') ...
    sprintf('Constant_XS_sn_comparions_S2SA_Gauss') ...
    sprintf('Constant_XS_sn_comparions_S2SA_Lobatto') ...
    sprintf('Constant_XS_c_comparions_S2SA_Gauss') ...
    sprintf('Constant_XS_c_comparions_S2SA_Lobatto') ...
    sprintf('Constant_XS_SN8_S2SA_Gauss') ...
    sprintf('Constant_XS_SN8_S2SA_Lobatto') ...
    sprintf('Const_2_Constant_XS_sn_comparions_MIP_Gauss') ...
    sprintf('Const_2_Constant_XS_sn_comparions_MIP_Lobatto') ...
    sprintf('Const_2_Constant_XS_c_comparions_MIP_Gauss') ...
    sprintf('Const_2_Constant_XS_c_comparions_MIP_Lobatto') ...
    sprintf('Const_4_Constant_XS_c_comparions_MIP_Gauss') ...
    sprintf('Const_4_Constant_XS_c_comparions_MIP_Lobatto') ...
... %     sprintf('Const_4_bar_Constant_XS_c_comparions_MIP_Gauss') ...
...    sprintf('Const_2_Constant_XS_SN8_MIP_Gauss') ...
...    sprintf('Const_2_Constant_XS_SN8_MIP_Lobatto') ...
 ...   sprintf('Const_4_Constant_XS_SN8_MIP_Gauss') ...
 ...   sprintf('Const_4_Constant_XS_SN8_MIP_Lobatto') ...
...    sprintf('Variable_XS_S2SA_Gauss_spr') ...
...    sprintf('Variable_XS_S2SA_Lobatto_spr') ...
...    sprintf('Const_4_Variable_XS_MIP_Gauss') ...
 ...   sprintf('Const_2_Variable_XS_MIP_Gauss') ...
...    sprintf('Const_2_Variable_XS_MIP_Lobatto') ...
...    sprintf('Const_4_Variable_XS_MIP_Gauss') ...
...    sprintf('Const_4_Variable_XS_MIP_Lobatto') ...
};

for i = 1:1:length(file_base_chapter_4)
     open(sprintf('%s/%s.fig',base_location,file_base_chapter_4{i} ) );
     SavePretty( gcf, sprintf('%s/%s',save_location,file_base_chapter_4{i} ) );
     close all;
end
